### ISSUE TITLE
TypeError: 'int' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by zuozijiZHOULI** [adocherty/node2vec_linkprediction#2]
Traceback (most recent call last):
  File "link_prediction.py", line 548, in <module>
    test_edge_functions(args)
  File "link_prediction.py", line 322, in test_edge_functions
    Gtrain, Gtest = create_train_test_graphs(args)
  File "link_prediction.py", line 300, in create_train_test_graphs
    directed=args.directed)
  File "link_prediction.py", line 109, in read_graph
    G.edges[edge[0]][edge[1]]['weight'] = 1
TypeError: 'int' object has no attribute '__getitem__'

**Comment by zpengc** [comment]
the error line is at **G.edges[edge[0]][edge[1]]['weight'] = 1**.
Just convert it to G[edge[0]][edge[1]]['weight'] = 1
